version: "3.4"

volumes:
  pravham_pg_data: {}

services:
  revproxy:
    container_name: revproxy
    build: nginx_revproxy
    depends_on:
      - webapp
      - asyncapp
    restart: always
    ports:
      - 8000:80
  db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: pravaham
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pravham_pg_data:/var/lib/postgresql/data
  redis:
    # Unlike the official Redis image, Bitnami's version is simpler to set up using environment variables
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  asyncapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "redis"
      - "db"
    environment:
      DB_HOST: db
      DB_NAME: pravaham
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_DSN: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: pravaham.settings.async_base
      GUNICORN_WORKERS: 4
    command:
      - async

    ports:
      - "8002:8002"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "redis"
      - "db"
      - "asyncapp"
    environment:
      DB_HOST: db
      DB_NAME: pravaham
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_DSN: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: pravaham.settings.base
      STREAM_SERVER: http://localhost:8002/

    ports:
      - "8001:8001"
  runfeed:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "redis"
      - "db"
      - "asyncapp"
    environment:
      DB_HOST: db
      DB_NAME: pravaham
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_DSN: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: pravaham.settings.async_base
      MASTODON_BEARER_TOKEN: ${MASTODON_BEARER_TOKEN}
    command:
      - bash
      - -c
      - "exit 0"
