version: '3.4'

volumes:
  pravham_pg_data: {}

services:
  db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: pravaham
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pravham_pg_data:/var/lib/postgresql/data
  redis:
    # Unlike the official Redis image, Bitnami's version is simpler to set up using environment variables
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'