"""
Django settings for pravaham project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

from configurations.values import BooleanValue, PositiveIntegerValue, Value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-xn@y=fdc9+kpk#w%f1krv4=_50*5no1%x=m%l+y)txn+o9c0p4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# Authorization
AUTH_USER_MODEL = "accounts.User"  # User substitution

# Application definition

FIRST_PARTY_APPS = ["accounts", "posts"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *FIRST_PARTY_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pravaham.urls.sync_urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pravaham.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DB_HOST = Value(environ_prefix=None, environ_name="DB_HOST", default="db")
DB_NAME = Value(environ_prefix=None, environ_name="DB_NAME", default="chemondis")
DB_SCHEMA = Value(environ_prefix=None, environ_name="DB_SCHEMA", default="public")
DB_USER = Value(environ_prefix=None, environ_name="DB_USER", default="postgres")
DB_PASS = Value(environ_prefix=None, environ_name="DB_PASS", default="postgres")
DB_PORT = PositiveIntegerValue(
    environ_prefix=None, environ_name="DB_PORT", default=5432
)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "options": "-c search_path=" + DB_SCHEMA,
        },
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASS,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "TEST": {
            "NAME": "test_" + DB_NAME,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

BASE_DIR = os.path.abspath(os.path.dirname(__name__))
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR + "/static",
]
STATIC_ROOT = BASE_DIR + "/staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REDIS_PASSWORD = Value(environ_prefix=None, environ_name="REDIS_PASSWORD", default=None)
REDIS_DSN = Value(
    environ_prefix=None, environ_name="REDIS_DSN", default="redis://redis:6379/1"
)

if REDIS_DSN:
    if REDIS_PASSWORD:
        scheme, host, path = urlsplit(REDIS_DSN)[:3]
        REDIS_DSN = urlunsplit([scheme, f":{REDIS_PASSWORD}@{host}", path, "", ""])

NOTIFICATION_POST = "notification.post"
LOG_LEVEL = Value(
    environ_prefix=None, environ_name="LOG_LEVEL", default="DEBUG" if DEBUG else "INFO"
)
LOG_JSON = BooleanValue(environ_prefix=None, environ_name="LOG_JSON", default=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "level": LOG_LEVEL,
        "handlers": ["console"],
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "text",
            "stream": "ext://sys.stdout",
        }
    },
    "formatters": {
        "text": {
            "format": "%(asctime)s %(levelname)s %(thread)d %(process)d %(module)s %(name)s %(message)s",
        },
    },
}
LOGIN_REDIRECT_URL = "/posts/lobby"
STREAM_SERVER = Value(environ_prefix=None, environ_name="STREAM_SERVER")
MASTODON_BEARER_TOKEN = Value(environ_prefix=None, environ_name="MASTODON_BEARER_TOKEN")
COMMON_STREAM = "common_stream"
